name: Modular CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # Job 1: Build
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B compile --file pom.xml

      - name: Generate JAR
        run: mvn package -DskipTests

      - name: List generated JAR
        run: |
          echo "JAR file details:"
          find target -name "*.jar" -type f -exec ls -lh {} \;

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/*.jar
          retention-days: 5

  # Job 2: Test
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run unit tests
        run: mvn test

      - name: Generate test report artifact
        run: |
          mvn surefire-report:report-only
          
          # Create directory for reports
          mkdir -p test-reports
          
          # Copy test reports
          cp -r target/surefire-reports test-reports/ || echo "No surefire-reports found"
          cp -r target/site test-reports/ || echo "No site reports found"
          
          # Create a summary file
          echo "TEST REPORT SUMMARY - $(date)" > test-reports/summary.txt
          echo "Repository: ${{ github.repository }}" >> test-reports/summary.txt
          echo "Branch: ${{ github.ref_name }}" >> test-reports/summary.txt
          
          # Extract test results summary
          if [ -d "target/surefire-reports" ]; then
            echo "Unit Test Results:" >> test-reports/summary.txt
            grep -r "Tests run:" target/surefire-reports/*.txt | sed 's/.*Tests run: \(.*\), Failures: \(.*\), Errors: \(.*\), Skipped: \(.*\)/\  - Tests: \1, Failures: \2, Errors: \3, Skipped: \4/' >> test-reports/summary.txt || echo "No test results found" >> test-reports/summary.txt
          fi

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: test-reports/
          retention-days: 5

  # Job 3: Deploy Infrastructure
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: application-jar
          path: target

      - name: Create specific JAR for Terraform
        run: |
          echo "Verifying downloaded JAR file:"
          find target -name "*.jar" -type f -exec ls -lh {} \;
          
          # Create the terraform/target directory
          mkdir -p terraform/target
          
          # Get the source JAR file
          SOURCE_JAR=$(find target -name "*.jar" -type f | head -1)
          echo "Found source JAR: $SOURCE_JAR"
          
          # Copy it to the specific file name Terraform is looking for
          cp "$SOURCE_JAR" "terraform/target/hello-api-test-0.0.1-SNAPSHOT-aws.jar"
          
          # Verify the specific file exists
          echo "Checking for specific JAR file required by Terraform:"
          ls -lh terraform/target/hello-api-test-0.0.1-SNAPSHOT-aws.jar

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: |
          cd terraform
          terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate
        env:
          AWS_REGION: us-east-1

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Extract API Gateway URL
        id: extract-url
        run: |
          cd terraform
          API_URL=$(terraform output -raw api_gateway_url || echo "")
          echo "api_url=$API_URL" >> $GITHUB_OUTPUT
          echo "API Gateway URL: $API_URL"
          
          # Save the URL to a file for artifact
          mkdir -p api-info
          echo "$API_URL" > api-info/api_url.txt

      - name: Upload API info as artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-details
          path: api-info
          retention-days: 1

  # Job 4: Integration Tests
  integration_test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    needs: terraform  # This dependency can't be removed as we need the API URL
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Download API details
        uses: actions/download-artifact@v4
        with:
          name: api-details
          path: api-info

      - name: Wait for API to be ready
        run: |
          # Read API URL from file
          API_URL=$(cat api-info/api_url.txt)
          echo "API Gateway URL: $API_URL"
          
          # Basic wait with retry
          MAX_RETRIES=30
          RETRY_COUNT=0
          
          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
            echo "Waiting for API to be ready... (attempt $((RETRY_COUNT+1))/$MAX_RETRIES)"
          
            # Try to call the API
            STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$API_URL" || echo "000")
          
            if [[ "$STATUS_CODE" == "200" ]] || [[ "$STATUS_CODE" == "403" ]] || [[ "$STATUS_CODE" == "404" ]]; then
              echo "API is responding with status code: $STATUS_CODE"
              break
            else
              echo "API not ready, got status code: $STATUS_CODE"
              sleep 10
              RETRY_COUNT=$((RETRY_COUNT+1))
            fi
          done
          
          if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
            echo "WARNING: Maximum retries reached. Proceeding anyway but API might not be ready."
          fi

      - name: Run integration tests
        run: mvn verify -P integration-test

      - name: Generate integration test report
        run: |
          # Create directory for reports
          mkdir -p integration-test-reports
          
          # Extract integration test results if available
          if [ -d "target/failsafe-reports" ]; then
            cp -r target/failsafe-reports integration-test-reports/
          
            # Create a summary
            echo "INTEGRATION TEST REPORT SUMMARY - $(date)" > integration-test-reports/summary.txt
            grep -r "Tests run:" target/failsafe-reports/*.txt | sed 's/.*Tests run: \(.*\), Failures: \(.*\), Errors: \(.*\), Skipped: \(.*\)/\  - Tests: \1, Failures: \2, Errors: \3, Skipped: \4/' >> integration-test-reports/summary.txt || echo "No test results found" >> integration-test-reports/summary.txt
          else
            echo "No integration test reports found" > integration-test-reports/summary.txt
          fi

      - name: Upload integration test reports
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-reports
          path: integration-test-reports/
          retention-days: 5

  # Job 5: Email Report
  email_report:
    name: Email Test Report
    runs-on: ubuntu-latest
    needs: [test, integration_test]
    if: always() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:
      - name: Download unit test reports
        uses: actions/download-artifact@v4
        with:
          name: unit-test-reports
          path: unit-test-reports/
        continue-on-error: true

      - name: Download integration test reports
        uses: actions/download-artifact@v4
        with:
          name: integration-test-reports
          path: integration-test-reports/
        continue-on-error: true

      - name: Combine test reports
        run: |
          mkdir -p combined-reports
          
          # Create email report
          echo "TEST REPORT SUMMARY - $(date)" > combined-reports/email-report.txt
          echo "Repository: ${{ github.repository }}" >> combined-reports/email-report.txt
          echo "Branch: ${{ github.ref_name }}" >> combined-reports/email-report.txt
          echo "Commit: ${{ github.sha }}" >> combined-reports/email-report.txt
          echo "Run URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> combined-reports/email-report.txt
          echo "" >> combined-reports/email-report.txt
          
          # Add unit test summary
          if [ -f "unit-test-reports/summary.txt" ]; then
            echo "UNIT TESTS:" >> combined-reports/email-report.txt
            cat unit-test-reports/summary.txt >> combined-reports/email-report.txt
            echo "" >> combined-reports/email-report.txt
          else
            echo "No unit test report available" >> combined-reports/email-report.txt
            echo "" >> combined-reports/email-report.txt
          fi
          
          # Add integration test summary
          if [ -f "integration-test-reports/summary.txt" ]; then
            echo "INTEGRATION TESTS:" >> combined-reports/email-report.txt
            cat integration-test-reports/summary.txt >> combined-reports/email-report.txt
          else
            echo "No integration test report available" >> combined-reports/email-report.txt
          fi

      - name: Send Email with Test Report
        uses: dawidd6/action-send-mail@v3.9.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Test Report for ${{ github.repository }} - Build #${{ github.run_number }}
          body: |
            Hello,
            
            The pipeline for ${{ github.repository }} has completed.
            Build #${{ github.run_number }} on branch ${{ github.ref_name }}
            
            Please find attached the test report summary.
            
            Full details are available at: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            Regards,
            CI/CD Pipeline
          to: lwazijiyane962@gmail.com
          from: CI Pipeline
          attachments: combined-reports/email-report.txt
        continue-on-error: true