name: Java CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests -Dmaven.compiler.source=11 -Dmaven.compiler.target=11

    - name: Run tests
      run: mvn test

    - name: Generate test report
      run: mvn surefire-report:report
      if: always()
      
    - name: Build JAR file
      run: mvn package -DskipTests
      
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v2
      with:
        name: application-jar
        path: target/*.jar
        retention-days: 7
        
