name: Java CI with Terraform

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dmaven.compiler.source=11 -Dmaven.compiler.target=11

      - name: Run tests
        run: mvn test

      - name: Generate JAR
        run: mvn package -DskipTests

      - name: List generated artifacts
        run: |
          echo "Listing files in target directory:"
          ls -la target/
          echo "JAR file details:"
          find target -name "*.jar" -type f -exec ls -lh {} \;

  terraform:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: |
          cd terraform
          terraform init
        env:
        # Add any necessary environment variables for Terraform backends
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan
        env:
        # Add any necessary environment variables for your Terraform providers
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # TF_VAR_app_version: ${{ github.sha }}