name: Modular CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # Step 1 & 2: Build and Test
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B compile --file pom.xml

      - name: Run unit tests
        run: mvn test

      - name: Generate JAR
        run: mvn package -DskipTests

      - name: List generated JAR
        run: |
          echo "JAR file details:"
          find target -name "*.jar" -type f -exec ls -lh {} \;

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v3
        with:
          name: application-jar
          path: target/*.jar
          retention-days: 1

  # Step 3: Deploy Infrastructure
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: application-jar
          path: terraform/target

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: |
          cd terraform
          terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate
        env:
          AWS_REGION: us-east-1

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Extract API Gateway URL
        id: extract-url
        run: |
          cd terraform
          API_URL=$(terraform output -raw api_gateway_url || echo "")
          echo "api_url=$API_URL" >> $GITHUB_OUTPUT
          echo "API Gateway URL: $API_URL"

      - name: Upload API URL as artifact
        uses: actions/upload-artifact@v3
        with:
          name: api-details
          path: terraform/terraform.tfstate
          retention-days: 1

  # Step 4: Integration Tests
  integration_test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: terraform
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Download API details
        uses: actions/download-artifact@v3
        with:
          name: api-details
          path: terraform/

      - name: Wait for API to be ready
        run: |
          # Improved waiting logic with timeout and health check
          API_URL=$(cd terraform && terraform output -raw api_gateway_url || echo "")
          echo "API Gateway URL: $API_URL"
          
          # Wait for the API to be ready with a timeout
          TIMEOUT=300  # 5 minutes
          START_TIME=$(date +%s)
          
          while true; do
            CURRENT_TIME=$(date +%s)
            ELAPSED_TIME=$((CURRENT_TIME - START_TIME))
          
            if [ $ELAPSED_TIME -gt $TIMEOUT ]; then
              echo "Timeout reached waiting for API to be ready"
              exit 1
            fi
          
            # Try to call the API
            HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$API_URL/health" || echo "000")
          
            if [[ "$HTTP_STATUS" == "200" ]]; then
              echo "API is ready (HTTP status: $HTTP_STATUS)"
              break
            else
              echo "API not ready yet (HTTP status: $HTTP_STATUS), waiting... (elapsed: ${ELAPSED_TIME}s)"
              sleep 10
            fi
          done

      - name: Run integration tests
        run: mvn verify -P integration-test

  # Step 5: Test Reports
  test_report:
    name: Generate Test Reports
    runs-on: ubuntu-latest
    needs: [build_and_test, integration_test]
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Download all test results
        uses: actions/download-artifact@v3
        with:
          path: artifacts/

      - name: Generate Test Reports
        run: |
          mvn surefire-report:report-only
          mvn site -DgenerateReports=false

      - name: Prepare test report
        run: |
          # Create directory for reports
          mkdir -p test-reports
          
          # Create a detailed summary for email
          echo "TEST REPORT SUMMARY - $(date)" > test-reports/email-report.txt
          echo "Repository: ${{ github.repository }}" >> test-reports/email-report.txt
          echo "Branch: ${{ github.ref_name }}" >> test-reports/email-report.txt
          echo "Commit: ${{ github.sha }}" >> test-reports/email-report.txt
          echo "Run URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> test-reports/email-report.txt
          echo "" >> test-reports/email-report.txt
          
          # Extract test results summary from surefire-reports
          if [ -d "target/surefire-reports" ]; then
            echo "Unit Test Results:" >> test-reports/email-report.txt
            grep -r "Tests run:" target/surefire-reports/*.txt | sed 's/.*Tests run: \(.*\), Failures: \(.*\), Errors: \(.*\), Skipped: \(.*\)/\  - Tests: \1, Failures: \2, Errors: \3, Skipped: \4/' >> test-reports/email-report.txt || echo "No test results found" >> test-reports/email-report.txt
            echo "" >> test-reports/email-report.txt
          
            # List any failed tests
            grep -r "<<< FAILURE!" target/surefire-reports/*.txt | sed 's/.*\(.*Test.*\)<<< FAILURE!.*/\  - Failed: \1/' >> test-reports/email-report.txt || echo "No test failures detected" >> test-reports/email-report.txt
          else
            echo "No test reports found in target/surefire-reports" >> test-reports/email-report.txt
          fi

      - name: Upload test report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: test-reports/
          retention-days: 5

  # Step 6: Email Report
  email_report:
    name: Email Test Report
    runs-on: ubuntu-latest
    needs: test_report
    if: always() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:
      - name: Download test reports
        uses: actions/download-artifact@v3
        with:
          name: test-reports
          path: test-reports/

      - name: Send Email with Test Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Test Report for ${{ github.repository }} - Build #${{ github.run_number }}
          body: |
            Hello,
            
            The pipeline for ${{ github.repository }} has completed.
            Build #${{ github.run_number }} on branch ${{ github.ref_name }}
            
            Please find attached the test report summary.
            
            Full details are available at: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            Regards,
            CI/CD Pipeline
          to: lwazijiyane962@gmail.com
          from: CI Pipeline
          attachments: test-reports/email-report.txt
        continue-on-error: true